### PR TITLE
Add an option to toggle the pilot dashboard

### PR DESCRIPTION
**Pull request by SantoDE**
Adds an option to toggle the pilot dashboard through the helm chart, which is a new option since 2.4.8

### CODE REVIEW

**Review by jakubhajek — APPROVED** [review]
LGTM :)

**Review by kevinpollet — APPROVED** [review]
LGTM

**Comment by DarthHTTP** [comment]
Gentlemen of the LGTM club :)
merged-merged but not tested :)

```
    pilot:
      enabled: false
      dashboard: false
```
just for the kicks, disables the ENTIRE dashboard.

192.168.1.X - - [28/Mar/2021:23:33:45 +0000] "GET /dashboard/ HTTP/1.1" 404 19 "-" "-" 12 "-" "-" 0ms

**Comment by kevinpollet** [comment]
Hello @DarthHTTP and thanks for your interest in Traefik,

I just tested what you said and everything is working as expected. Disabling Pilot and its dashboard does not disable the entire dashboard for Traefik, so something might be wrong on your side.

If you still thinking that there is a bug, feel free to open an issue with more details and a reproducible case.

**Pull request merged**
