### PR TITLE
Revert split LoadBalancers to single LoadBalancer with mixed protocols

### PR DESCRIPTION
**Pull request by 0xThiebaut**
Commit 6d60914 acted as a work-around for LoadBalancers' single protocol requirement (see [bergmannf's comment](https://github.com/traefik/traefik-helm-chart/pull/145#issuecomment-610791540) on #145). Kubernetes now supports LoadBalancers with mixed protocols (kubernetes/kubernetes#94028).

This commit reverts the original work-around to reintroduce a single TCP/UDP LoadBalancer for Traefik, cutting LoadBalancer costs in half.

_Note: The mixed-protocol LoadBalancers are planned to be included in [Kubernetes milestone v1.20](https://github.com/kubernetes/kubernetes/milestone/48)._

### CODE REVIEW

**Comment by 0xThiebaut** [comment]
As this PR relies on Kubernetes 1.20, a backwards-compatibility check could be introduced to rely on the current implementation for pre-1.20 clusters.

**Comment by SantoDE** [comment]
Hello @0xThiebaut,

thanks for your PR.

Can you add some unit test please? :)

**Comment by 0xThiebaut** [comment]
Yes, will add some this week.

**Comment by SantoDE** [comment]
Hello @0xThiebaut,

any updates? :)

**Comment by 0xThiebaut** [comment]
I am not that familiar with the testing suite. Do you have any advise on how I can ensure the testing suite behaves differently depending on the Kubernetes version?

From the [helm-unittest documentation](https://github.com/rancher/helm-unittest/blob/master/DOCUMENT.md) it seems quite limited and the current service's UDP test will definitely fail given it looks for the second LoadBalancer which will now be out of bounds if Kubernetes v1.20+ is used.

**Comment by Elegant996** [comment]
Since the mixed protocols is beta as of 1.24, we should looking at updating this PR with proper testing and merging it.

**Comment by mloiseleur** [comment]
Superseded by #656

**Pull request closed without merging**
