### PR TITLE
Add basic auth for the exposed dashboard

### PR DESCRIPTION
**Pull request by walbertus**
Users will be able to specify the username and password used to login to the dashboard.
Setting the username and password is mandatory when the user chooses to expose the dashboard.

This PR will help #186

### CODE REVIEW

**Comment by SantoDE** [comment]
Hello @walbertus,

Thanks for you work so far :-)

Let me know once you have a PR state we can test. Should I test the current version already?

**Comment by walbertus** [comment]
Hi @SantoDE 

You can test this PR now but you need to specify the password, as there's no mechanism to print generated password yet.

**Comment by walbertus** [comment]
Updates:
 - Dashboard password is now mandatory

Issues:
 - Basic auth uses MD5, SHA1, or BCrypt for encryption ([here](https://docs.traefik.io/middlewares/basicauth/#general)). Helm support some methods related to cryptography ([here](https://helm.sh/docs/chart_template_guide/function_list/#cryptographic-and-security-functions)).
These methods only intersect at `htpasswd`, which failed on pipeline with error `function "htpasswd" not defined`.

Do you have any suggestion about this @SantoDE ?

**Comment by SantoDE** [comment]
Hello @walbertus,

sorry for answering a little late :)

Hmm, not sure about your issue tough. Maybe it would be an option to use a sha1sum on the provided password and run this through a b64 enc before writing to the secret? Does it make sense?

**Comment by walbertus** [comment]
Hello @SantoDE,

That's a nice idea, user can generate their own credentials using whatever encryption they choose.

Will update this

**Comment by SantoDE** [comment]
@walbertus can I give it another test? Did you found a way for the credential "delivery?

**Comment by SantoDE** [comment]
Hey @walbertus,

any updates?

**Comment by walbertus** [comment]
Hi @SantoDE sorry I miss your comment
User-generated credentials are the only way I think, do you have any other suggestion?

Will resolve the conflict after work

**Comment by CuBiC3D** [comment]
Hey I kinda think, that `userData` sounds a little bit misleading as it suggests to provide some data by the user and not user auth related settings. And generated secrets by Helm should also provide an option to be self provided by secret name, since people use GitOps nowdays with sealed secrets or SOPS and really don't like to have those things be gitted as values.

**Comment by SantoDE** [comment]
I agree with you @CuBiC3D, at least if I understood correctly. Any ideas how we wanna move that forward?

**Comment by CuBiC3D** [comment]
I would just suggest to rename `userData` to something like `usersString` or `users` (one could probably expect an array here) and create `useExistingSecret` and `secretName` values to define those (first one could be omitted since an empty secret name can also be used as a condition).

**Comment by walbertus** [comment]
I agree `userData` is misleading. `users` seems more appropriate since Traefik also uses [users](https://docs.traefik.io/middlewares/basicauth/#users).

We can also use the `useExistingSecret` filled with the secret name

WDYT?

**Comment by SantoDE** [comment]
Sounds good in theory. Eager to see it :)

**Pull request closed without merging**
