### PR TITLE
Only create one Service based on version check

### PR DESCRIPTION
**Pull request by valerauko**
This is the continuation of #311. I cherry-picked @0xThiebaut's commits and added the tests as requested in #311.

Since the rancher-maintained helm-unittest does not support mocking Capabilities, I switched to an apparently [better-maintained other fork](https://github.com/quintush/helm-unittest).

### CODE REVIEW

**Comment by valerauko** [comment]
Ping @SantoDE since you asked for tests in the original PR

**Comment by valerauko** [comment]
On the other hand, using this still requires a feature gate enabled in the apiserver...

https://kubernetes.io/docs/concepts/services-networking/service/#load-balancers-with-mixed-protocol-types

**Comment by Elegant996** [comment]
Saw that this PR actually has the testing. Could we update the version from 1.20 to 1.24 for Kubernetes? Mixed protocol is now beta and is enabled by default going forward.

**Comment by mloiseleur** [comment]
Superseded by #656

**Pull request closed without merging**
