### PR TITLE
fix semver compare

### PR DESCRIPTION
**Pull request by DirtyCajunRice**
* tag was forced causing chart appversion to be unused and redundant
* version didnt always return a sane semver as compare expected whereas gitversion does

### CODE REVIEW

**Comment by SantoDE** [comment]
Hey @DirtyCajunRice,

can you describe what's currently failing please? Just a PR without a description is a little hard ;-)

**Comment by DirtyCajunRice** [comment]
> Hey @DirtyCajunRice,
> 
> 
> 
> can you describe what's currently failing please? Just a PR without a description is a little hard ;-)

@SantoDE updated description

**Comment by SantoDE** [comment]
Thanks @DirtyCajunRice. Sadly, I still can't follow really :(

Why it is "better" or more sane in the GitVersion rather than in the Kube Version? And what is more convenient with the default App version? I'm sorry, but I need more explanation. I feel lost in why this is "better"

**Comment by DirtyCajunRice** [comment]
@SantoDE  I actually did not realize that kube had slipped GitVersion into deprecated state. I have changed this to remove the semvercompare altogether and instead checked for the proper apiversion. This sanely decouples a hard number being placed in the yaml and instead better ensures that the apiversion exists. Doing this will remove the possible edge case where the version is correct but the apiversion is missing.

**Comment by DirtyCajunRice** [comment]
@SantoDE I have resolved merge conflicts post TLS merge :)

**Review by SantoDE — APPROVED** [review]
LGTM 👼

**Pull request merged**
