### PR TITLE
Add missing tracing options

### PR DESCRIPTION
**Pull request by uroshercog**
### What does this PR do?
Adds support for all tracing options available in Traefik.

### More

- [x] Yes, I updated the [chart version](https://github.com/traefik/traefik-helm-chart/blob/9b32ed1b414cc0be1ad46bcb335fcfc93ded06f3/traefik/Chart.yaml#L5)

### CODE REVIEW

**Comment by MoonFalcon** [comment]
Any update on this?

**Comment by gibbonsryan** [comment]
Bump.

**Comment by charlie-haley** [comment]
Thanks for the PR @uroshercog, the changes look good to me! Could you update your branch?

**Review by charlie-haley — APPROVED** [review]
LGTM!

**Pull request merged**
