### PR TITLE
feat: Add ingressclass

### LINKED ISSUE #234: Add IngressClass for upcoming 2.3 Release
Lock behind a kube version check of 1.18.x

### PR DESCRIPTION
**Pull request by DirtyCajunRice**
Fixes #234

### CODE REVIEW

**Comment by SantoDE** [comment]
Hello @DirtyCajunRice,

thanks for the PR :-)

I'll see what you did and I like, but it won't be working until 2.3 GA. Not sure if we want to merge that before? Any thoughts on that?

**Comment by DirtyCajunRice** [comment]
Right it will not. Since the gate is there it could either sit until 2.3GA or get merged now and it would "effectively" be the same. Doesnt really matter its your call.

**Comment by SantoDE** [comment]
Hi @DirtyCajunRice,

we're prepping the helm-chart release of 2.3. I'm wondering, if you should merge the PR's for that. Are you okay with me, cherry-picking your work into a PR to bump the versions?

**Comment by DirtyCajunRice** [comment]
@SantoDE No concerns here. Im available today as well - anything i can do to help?

**Comment by SantoDE** [comment]
As #267 is merged, I'll close that one.

Thanks 👍

**Pull request closed without merging**
