### PR TITLE
Version bumped 2.4.13

### PR DESCRIPTION
**Pull request by jakubhajek**
### What does this PR do?

Upgrading Traefik to 2.4.13

### Motivation

The new version of Traefik has been recently released. 

### More

- [x] Yes, I updated the [chart version](https://github.com/traefik/traefik-helm-chart/blob/9b32ed1b414cc0be1ad46bcb335fcfc93ded06f3/traefik/Chart.yaml#L5)

### Additional Notes

N/A

### CODE REVIEW

**Comment by Tchoupinax** [comment]
Hello,

What's up with this PR ? :) The bumped version may be increased to 2.4.12 (<https://github.com/traefik/traefik/releases/tag/v2.4.12>)

**Comment by mnorrsken** [comment]
Afaik there is breaking changes between 2.4.9 and later:
v2.4.9 to v2.4.10
K8S CrossNamespace
In v2.4.10, the default value for allowCrossNamespace has been changed to false.

K8S ExternalName Service
In v2.4.10, by default, it is no longer authorized to reference Kubernetes ExternalName services. To allow it, the allowExternalNameServices option should be set to true.

It would be nice if the chart values had settings to enable these instead of having to use additonalArguments

It could even be a good idea to set these to "true" in the chart, or at least make a note about this when upgrading from a pre 2.4.11 version

**Comment by docwhat** [comment]
This should probably be bumped in priority due to the security advisory [_Drop Headers via Malicious Connection Header_](https://github.com/traefik/traefik/security/advisories/GHSA-m697-4v8f-55qg)

**Review by SantoDE — APPROVED** [review]
LGTM :)

**Comment by Tchoupinax** [comment]
According to the message of @mnorrsken, there is no change about the breaking change came with 2.4.10 ?

**Comment by mnorrsken** [comment]
To keep the 2.4.9 defaults, add this to values.yaml:

```
additionalArguments:
  - "--providers.kubernetescrd.allowcrossnamespace=true"
  - "--providers.kubernetescrd.allowexternalnameservices=true"
  - "--providers.kubernetesingress.allowexternalnameservices=true"
```

Of course review if you really need these options first.

**Pull request merged**
