### PR TITLE
Add notes about CRDs not applied when upgrading chart

### PR DESCRIPTION
**Pull request by mnorrsken**
#343 

Tested locally:
```
NOTES:
######## Upgrade information ########

If upgrading from Traefik version 2.3 or earlier please reinstall helm chart or apply CRDs manually:

kubectl apply -f https://raw.githubusercontent.com/traefik/traefik-helm-chart/v9.13.0/traefik/crds/serverstransports.yaml
$ kubectl apply -f https://raw.githubusercontent.com/traefik/traefik-helm-chart/v9.13.0/traefik/crds/serverstransports.yaml
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io/serverstransports.traefik.containo.us unchanged
```

Disclaimer: English is not my first language.

Also unsure about the {{ .Chart.Version }} variable in the URL name

### CODE REVIEW

**Comment by mnorrsken** [comment]
I’m not sure why CI is not reporting green, is it something with LINT not recognizing the NOTES? Anyway this could propably be handled by adding some explicit documentation to traefik docs too.

**Comment by SantoDE** [comment]
Because it needs a minor version bump  to `9.14.2`

**Comment by SantoDE** [comment]
Hey @mnorrsken,

can we maybe make the download instructions to download all files in the directory, rather then just 1 file? That would be better maintainable for the future.

**Comment by mloiseleur** [comment]
Hello @mnorrsken,

With PR #649, we added more information on how to upgrade CRDs and we provided a one-command way to do it.

Before closing this PR, is there anything we missed and you think we should add on this topic ?

**Comment by mnorrsken** [comment]
Norhing to add, excellent work :)

mån 10 okt. 2022 kl. 18:13 skrev mloiseleur ***@***.***>:

**Pull request closed without merging**
