### PR TITLE
Implement support for DaemonSet

### PR DESCRIPTION
**Pull request by davidalger**
**What this PR does:**

Implements support for deploying Traefik using a DaemonSet rather than a Deployment. In order to minimize duplicate code (and ensure long-term parity) the PodTemplate has been moved to a .tpl and included into the template definition on both the Deployment and DaemonSet resource definitions.

Based on the discussion / comments [here](https://github.com/traefik/traefik-helm-chart/pull/56#issuecomment-713865110) and [here](https://github.com/traefik/traefik-helm-chart/pull/56#issuecomment-715046408) this PR fully acknowledges the inability to support DaemonSet _in combination with_ ACME and as such helm will emit the following error in the event a user should attempt such an installation (similar to the error currently emitted when deployment.replicas is > 1 and ACME is configured):

```
$ helm install traefik ./traefik-helm-chart/traefik --set deployment.kind=DaemonSet --set additionalArguments={--certificatesresolvers.le.acme.storage=/data/acme.json}
Error: template: traefik/templates/daemonset.yaml:5:12: executing "traefik/templates/daemonset.yaml" at <fail (printf "ACME functionality is not supported when running Traefik as a DaemonSet")>: error calling fail: ACME functionality is not supported when running Traefik as a DaemonSet
```

Having this guard rail in place should alleviate concerns about the chart being used to deliver an officially unsupported configuration into production while allowing this chart to be employed by end users in the many scenarios for which a DaemonSet better suited than a Deployment.

**Related issues and PRs:**
- #141 
- #93 
- #56 
- #54 
- helm/charts#11813

cc @dduportal @notsureifkevin @SantoDE

### CODE REVIEW

**Comment by SantoDE** [comment]
Hello @davidalger,

thanks for this PR and sorry for the long time no answer. As you know, thats a highly discussed topic.

Be aware - Im still discussing with the other maintainers on that one. But we are on it.

**Comment by SantoDE** [comment]
Hello @davidalger,

well, that went quickly :)

We looked at the PR and we think, it could be a good addition. Do you have the time to do a rebase and fix the conflict? Or do you want us to do it?

**Comment by davidalger** [comment]
@SantoDE I've rebased the PR, making sure to manually copy the latest pod spec into the .tpl to ensure we won't lose any changes made in there by other PRs that were merged ahead of this one.

**Comment by SantoDE** [comment]
I also just did run a rebase with the podlabels PR merged. Im wondering tough: We dont have any unit tests for the deamonset yet. Its rather only for the deployment. Can you add some please?

**Comment by SantoDE** [comment]
Hello @davidalger,

any updates here? :) Id like to merge that one.

**Comment by davidalger** [comment]
@SantoDE Just pushed an update adding a couple tests for the daemonset template, and moved the bulk of the tests from deployment into the pod-config test file where they were testing what's generated (and shared by both) for spec.template. Lmk if anything else is needed to move this along. Thanks!

**Review by SantoDE — APPROVED** [review]
LGTM 👼 

Tested it for a fair amount of time and it works great. Thanks for your work.

**Comment by mzac** [comment]
Worked great!  I just upgraded two of my k3s installs and now the daemonset is running!!

**Pull request merged**
