### PR TITLE
Template custom volume name

### PR DESCRIPTION
**Pull request by steven-sheehy**
This passes `volumes[].name` through tpl so it can be templated. This is necessary because the extra volumes name is either a ConfigMap or Secret and those usually contain the dynamic Helm release name. For example:
```yaml
  volumes:
    - name: '{{ printf "%s-traefik" .Release.Name }}'
      mountPath: /etc/traefik/
      type: configMap
```

### CODE REVIEW

**Comment by steven-sheehy** [comment]
It is required if you have more than one Traefik deployment, especially in Helm 2 where releases are global. It is best practice to include the release name in all Kubernetes objects to avoid conflicts on install. Right now the chart requires a static value like `traefik` for volume name so you can't install multiple Traefiks. We had to revert from using a ConfigMap volume to configure Traefik to using the CLI arguments until this could be fixed.

**Comment by SantoDE** [comment]
Hello @steven-sheehy,

sorry for the long no reply. I agree, it makes sense to have it. Can you rebase to the current state?

**Comment by steven-sheehy** [comment]
Thanks @SantoDE. I've fixed the conflicts.

**Comment by steven-sheehy** [comment]
Fixed conflict

**Comment by SantoDE** [comment]
Thanks! Sorry for the hiatus.

One question: Is that a potential breaking change? Like, will old volume names still work? It will, right? Just wondering about the helm-chart version.

**Comment by steven-sheehy** [comment]
Yes, it is backwards compatible with non-templated volumes. I've added a test for that scenario.

**Comment by SantoDE** [comment]
Thank you @steven-sheehy

**Pull request merged**
