### PR TITLE
Acme json fix persistence enabled

### LINKED ISSUE #396: acme resolver not working with persistence enabled
The acme resolver isn't working with persistence enabled due to file permissions.

See below the log.

```bash
time="2021-03-22T11:03:24Z" level=error msg="The ACME resolver \"le\" is skipped from the resolvers list because: unable to get ACME account: permissions 660 for /data/acme.json are too open, please use 600"
```

This is an abstract of my values.yml

```
additionalArguments:
  - "--serverstransport.insecureskipverify=true"
  - "--certificatesresolvers.le.acme.dnschallenge=true"
  - "--certificatesresolvers.le.acme.email=me@tld.com"
  - "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
  - "--certificatesresolvers.le.acme.storage=/data/acme.json"

persistence:
  enabled: true

serviceAccountAnnotations:
  eks.amazonaws.com/role-arn: <<my_arn_with_a_policy_for_route53>>
```

### PR DESCRIPTION
**Pull request by marcofranssen**
resolves #396 without the need for chart users to think about adding this initContainer.

### CODE REVIEW

**Review by jakubhajek — COMMENTED** [review]
Thanks for that PR. 

The init containers that set permission to 600 on `/data/*` is already implemented and ready to use.

**Review by jakubhajek — COMMENTED** [review]
The init containers that set permission to 600 on /data/* is already implemented and ready to use.

**Comment by SantoDE** [comment]
Thanks @jakubhajek 

I gonna close that PR then :)

**Comment by marcofranssen** [comment]
Where can I see this? It is not part of the master branch. Thats why I opened this PR.

**Comment by jakubhajek** [comment]
Hello @marcofranssen 👋 

Thanks a lot for opening the PR. We appreciate your interest and always warmly welcome new changes addressed by our community members.

Again, we have just discussed the issue internally together with @SantoDE. We are aware that in specific circumstances there might happen the issue with permissions to the file where Traefik stores SSL certificates (/data/acme.json). Here are other related issues reported by the community: [#6825](https://github.com/traefik/traefik/issues/6825#issuecomment-631450807), [#6972](https://github.com/traefik/traefik/issues/6972)

Our statement is that the operator *should be aware* of the state of their filesystem. That's why we had introduced `initContainers` feature - that has to be enabled *manually* -  a tiny busy box container that fixes the permission but only in the situation when it is required.  

Implementing the change on the pod_template level will lead to the situation that `initContainer`will be always executed when the persistence is enabled even if it is not required. 

However, there are other solutions in progress. There is already PR opened  [#7351](https://github.com/traefik/traefik/pull/7351) that allows storing certificates in Kubernetes secrets. Once it will be implemented and merged the persistence storage feature will be removed. 

Please let me know if you any other questions or remarks. Thank you,

**Comment by marcofranssen** [comment]
Great that is a clear explanation. Looking forward to the GH secrets change. That would be awesome.

**Pull request closed without merging**
