### PR TITLE
Added templating capabilities for pod anti-affinity

### PR DESCRIPTION
**Pull request by paulcrecan**
Added templating capabilities for pod anti-affinity

### CODE REVIEW

**Review by SantoDE — CHANGES_REQUESTED** [review]
Hello @paulcrecan,

thanks for your contribution.

2 things:

a) Can you rebase to get up2date please?
b) Can you provide an example of how it looks before and after your suggested enhancement right from the values? Im having a somewhat hard time to see what this will enable users to do :)

**Comment by paulcrecan** [comment]
Hi @SantoDE,

This changes will enable users to template the values used for the affinity section. For example, it will be possible to use the helm release specific values (e.g. .Release.Name, .Release.Namespace..). Basically, this will run the go templating engine for the values that contains a template. An example value for affinity:

`affinity: {
  "podAntiAffinity": {
    "requiredDuringSchedulingIgnoredDuringExecution": [
      {
        "labelSelector": {
          "matchExpressions": [
            {
              "key": "app.kubernetes.io/name",
              "operator": "In",
              "values": [
                '{{ template "traefik.name" . }}'
              ]
            },
            {
              "key": "app.kubernetes.io/name",
              "operator": "In",
              "values": [
                '{{ .Release.Name }}'
              ]
            },
          ]
        },
        "topologyKey": "kubernetes.io/hostname"
      }
    ]
  }
`

**Comment by reitermarkus** [comment]
Any update on this?

**Comment by faust64** [comment]
It would be nice to have some tests, maybe even comments. It isn't obvious to me what that code does, just looking at the diff.
Though I kinda get it, as I also noticed templating wasn't working in values, adding topologySpreadConstraints with #466

**Comment by mloiseleur** [comment]
Duplicates of #584.

**Comment by reitermarkus** [comment]
> Duplicates of https://github.com/traefik/traefik-helm-chart/pull/584.

@mloiseleur, I don't see how that PR is related to this PR.

**Comment by reitermarkus** [comment]
I guess you meant https://github.com/traefik/traefik-helm-chart/pull/557.

**Pull request closed without merging**
